Clase38/IntroduccionMVC/Controllers/UserController.cs
using IntroduccionMVC.Data;
using IntroduccionMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace IntroduccionMVC.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            var ctx = new ApplicationDbContext();

            var usuarios = ctx.Users.ToList();

            List<UserViewModel> models = new List<UserViewModel>();

            foreach (var item in usuarios)
            {
                UserViewModel user = new UserViewModel()
                {
                    Id = item.Id,
                    UserName = item.UserName
                };

                models.Add(user);
            }

            return View(models);

            //Para devolver una vista especifica segun su nombre
            //return View("Ejemplo");

        }


        public IActionResult Detalle(string id)
        {
            var ctx = new ApplicationDbContext();

            var usuario = ctx.Users.FirstOrDefault(x => x.Id == id);

            UserViewModel model = new UserViewModel()
            {
                Id = usuario.Id,
                UserName = usuario.UserName
            };

            return View(model);

            //Para devolver una vista especifica segun su nombre
            //return View("Ejemplo");

        }
    }
}

Clase38/IntroduccionMVC/Controllers/VehicleController.cs
using IntroduccionMVC.Data;
using IntroduccionMVC.Data.Entities;
using IntroduccionMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace IntroduccionMVC.Controllers
{
    public class VehicleController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        
        public VehicleController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        //Vista Lista
        public IActionResult Index()
        {
            var vehiculos = _dbContext.Vehiculos.ToList();

            //var model = new VehicleListViewModel
            //{
            //    Vehiculos = new List<VehicleListModel>()
            //};

            //foreach(var vehiculo in vehiculos)
            //{
            //    model.Vehiculos.Add(new VehicleListModel
            //    {
            //        Id = vehiculo.Id,
            //        Dominio = vehiculo.Dominio,
            //        AnioFabricacion = vehiculo.AnioFabricacion
            //    });
            //}

            var vehiclesList = vehiculos
                .Select(v => new VehicleListModel
                {
                    Id = v.Id,
                    Dominio = v.Dominio,
                    AnioFabricacion = v.AnioFabricacion
                })
                .ToList();

            ViewData["miTitulo"] = "My Vehicles";
            // ViewData["Vehicles"] = vehiclesList;

            ViewBag.Vehicles = vehiclesList;

            return View("List");
        }

        //Vista Nuevo
        public IActionResult New()
        {
            return View();
        }

        //Vista Editar
        public IActionResult Edit(int id)
        {
            if (_dbContext.Vehiculos.Any(x => x.Id == id))
            {
                VehicleModel modelo = _dbContext.Vehiculos.Select(v => new VehicleModel
                {
                    Id = v.Id,
                    NumeroChasis = v.NumeroChasis,
                    Dominio = v.Dominio,
                    AnioFabricacion = v.AnioFabricacion,
                    Propietario = v.Propietario
                }).First(x => x.Id == id);

                return View(modelo);
            }

            return RedirectToAction("Error", "Home");   
        }

        //Vista Eliminar
        public IActionResult Remove(int id)
        {
            if (_dbContext.Vehiculos.Any(x => x.Id == id))
            {
                VehicleModel modelo = _dbContext.Vehiculos.Select(v => new VehicleModel
                {
                    Id = v.Id,
                    NumeroChasis = v.NumeroChasis,
                    Dominio = v.Dominio,
                    AnioFabricacion = v.AnioFabricacion,
                    Propietario = v.Propietario
                }).First(x => x.Id == id);

                return View(modelo);
            }

            return RedirectToAction("Error", "Home");
        }

        //Vista Detalle
        public IActionResult Detail(int id)
        {
            if (_dbContext.Vehiculos.Any(x => x.Id == id))
            {
                VehicleModel modelo = _dbContext.Vehiculos.Select(v => new VehicleModel
                {
                    Id = v.Id,
                    NumeroChasis = v.NumeroChasis,
                    Dominio = v.Dominio,
                    AnioFabricacion = v.AnioFabricacion,
                    Propietario = v.Propietario
                }).First(x => x.Id == id);

                return View(modelo);
            }

            return RedirectToAction("Error", "Home");
        }

        //Post
        [HttpPost] 
        public async Task<IActionResult> Create (VehicleModel vehiculo)
        {
            if (!ModelState.IsValid)
            {
                //Registro de Log
                return View("New",vehiculo);
            }

            try
            {
                Vehiculo v = new()
                {
                    Dominio = vehiculo.Dominio,
                    AnioFabricacion = vehiculo.AnioFabricacion,
                    NumeroChasis = vehiculo.NumeroChasis,
                    Propietario = vehiculo.Propietario
                };

                _dbContext.Add(v);
                await _dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
                //throw;
            }
        }

        //Post
        [HttpPost]
        public async Task<IActionResult> Update(VehicleModel vehiculoModel)
        {
            try
            {
                if (_dbContext.Vehiculos.Any(x => x.Id == vehiculoModel.Id))
                {
                    Vehiculo vehiculoUpdate = _dbContext.Vehiculos.Select(v => new Vehiculo
                    {
                        Id = v.Id,
                        Dominio = vehiculoModel.Dominio,
                        NumeroChasis = vehiculoModel.NumeroChasis,
                        Propietario = vehiculoModel.Propietario,
                        AnioFabricacion = vehiculoModel.AnioFabricacion
                    }).First(x => x.Id == vehiculoModel.Id);

                    _dbContext.Update(vehiculoUpdate);
                    await _dbContext.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
                //throw;
            }
        }


        //Post
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                if (_dbContext.Vehiculos.Any(x => x.Id == id))
                {
                    Vehiculo vehiculoDelete = _dbContext.Vehiculos.First(x => x.Id == id);

                    _dbContext.Remove(vehiculoDelete);
                    await _dbContext.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
                //throw;
            }
        }

    }
}

Clase38/IntroduccionMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntroduccionMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntroduccionMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntroduccionMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Vehicles
                          </a>
                          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" asp-controller="Vehicle" asp-action="Index" >Vehicle List</a></li>
                            <li><a class="dropdown-item" asp-controller="Vehicle" asp-action="New" >New Vehicle</a></li>
                          </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IntroduccionMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>